name: "HA Entity Explorer"
version: "1.0.1"
slug: "ha_entity_explorer"
description: "Explore and visualize history of any Home Assistant entity."
url: "https://github.com/yourusername/ha_entity_explorer"
image: "kipk/ha-entity-explorer-{arch}"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
map:
  - config:rw
options:
  log_level: info
  language: "en"
  default_history_days: 4
  whitelist: []
  blacklist: []
  safe_ips: []
  auth_users: []
schema:
  log_level: list(debug|info|warning|error)
  language: list(fr|en)
  default_history_days: int
  whitelist:
    - str
  blacklist:
    - str
  safe_ips:
    - str
  auth_users:
    - username: str
      password: str
ports:
  8050/tcp: 8050

# API Access Permission
homeassistant_api: true

# Ingress support
ingress: true
ingress_port: 8050
panel_icon: "mdi:chart-timeline"
panel_admin: false
